// Public report page — no auth required, standalone layout
// Fetches report data by slug from Supabase (with mock fallback)

import { getReportById, getReportSections, MOCK_REPORTS, type StatusReport, type ReportSection } from "../../../../lib/mock-data";

interface ReportPageProps {
  params: Promise<{ slug: string }>;
}

export default async function ReportPage({ params }: ReportPageProps) {
  const { slug } = await params;

  // Try to find report by slug (mock for now)
  const report = MOCK_REPORTS.find((r) => r.slug === slug) ?? null;
  const sections = report ? getReportSections(report.id) : [];

  if (!report) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Report Not Found</h1>
          <p className="text-gray-500 max-w-sm">
            This report may have been removed or the link may be incorrect.
            Please contact your CrossnoKaye representative for assistance.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Report header */}
      <header className="border-b border-gray-100 py-8 px-6 print:border-none">
        <div className="mx-auto max-w-3xl">
          <div className="flex items-center justify-between mb-6">
            <span className="text-sm font-bold text-gray-900">
              ATLAS<span className="text-[#91E100]"> Collaborate</span>
            </span>
            <span className="text-xs text-gray-400">CrossnoKaye</span>
          </div>

          {/* Customer info */}
          <div className="flex items-center gap-3 mb-4">
            <div className="h-10 w-10 rounded-lg bg-gray-100 flex items-center justify-center">
              <span className="text-sm font-bold text-gray-400">
                {report.customerName.charAt(0)}
              </span>
            </div>
            <div>
              <p className="text-sm font-medium text-gray-900">{report.customerName}</p>
              {report.siteName && (
                <p className="text-xs text-gray-500">{report.siteName}</p>
              )}
            </div>
          </div>

          <h1 className="text-3xl font-bold text-gray-900">{report.title}</h1>
          <p className="mt-2 text-sm text-gray-500">
            Reporting period: {report.dateRangeStart} to {report.dateRangeEnd}
          </p>
          {report.publishedAt && (
            <p className="text-xs text-gray-400 mt-1">
              Published {new Date(report.publishedAt).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </p>
          )}
        </div>
      </header>

      {/* Report body */}
      <main className="mx-auto max-w-3xl px-6 py-8">
        {sections.length === 0 ? (
          <div className="rounded-xl border border-gray-100 p-8 text-center text-gray-400">
            This report has no content yet.
          </div>
        ) : (
          <div className="space-y-8">
            {sections
              .sort((a, b) => a.sortOrder - b.sortOrder)
              .map((section) => (
                <section key={section.id}>
                  <h2 className="text-lg font-bold text-gray-900 mb-3 pb-2 border-b border-gray-100">
                    {section.title}
                  </h2>
                  <div className="prose prose-sm max-w-none text-gray-700">
                    <p className="whitespace-pre-wrap leading-relaxed">{section.content}</p>
                  </div>
                </section>
              ))}
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-6 px-6 print:border-none">
        <div className="mx-auto max-w-3xl flex items-center justify-between text-xs text-gray-400">
          <span>Generated by ATLAS Collaborate</span>
          <span>CrossnoKaye</span>
        </div>
      </footer>
    </div>
  );
}
